site_name: My Notes
nav:
    - Home: index.md
    - Bacula: bacula.md
    - Base64: base64.md
    - Bash Stuff: bashstuff.md
    - FFMEG: ffmpeg.md
    - GiT: git.md
    - Keybase: keybase.md
    - Linux User Admin: linuxuser.md
    - Linux Tape Drives: linuxtapedrives.md
    - LVM - Linux Volume Manager: lvm.md
    - MAC - Apple: mac_apple.md
    - Markdown: markdown.md
    - Mount LUKS Encrypted Media: luksmount.md
    - MariaDB/MySQL: mysql.md
    - PGP: pgp.md
    - RDesktop: rdesktop.md
    - SSH: ssh.md
    - VI Editor: vi_editor.md
    - X11 Forwarding: x11_forwarding.md
theme: readthedocs
